title: James Lu # your name (or website title) here
logo: "/images/profile_pic.jpg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  As a data scientist, I have worked on a variety of projects that demonstrate my skills in data engineering, data analysis, machine learning, and visualization.
  Below are some projects I have undertaken including some key insights and deliverables from each.
  <br><br>
  Second description 
  <br><br>
  <a href="https://www.linkedin.com/in/example/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
